version: "3.8"

services:
  database:
    build: .
    ports:
      # choose an open port if you can't use 5432.
      # the first port is the port of your local machine
      - "5432:5432"
    volumes:
      - monsterdb-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    # set environment variables for postgres

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=monsterdb
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 9090:8080
      
    # usage of adminer:
    # http://localhost:9090
    # for server fill in 'database'

    
volumes:
  monsterdb-data: # named volumes can be managed easier using docker-compose

